@protocol = http
@host = localhost
@port = 4000

@hostname = {{protocol}}://{{host}}:{{port}}
@contentType = application/json

### Login
# @name login
POST {{hostname}}/api/Authentication/Register HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "bucovala.sebastian@protonmail.com",
    "username": "bucovalasebastian",
    "password": "Tg6o0xqjlx#"
}

@authToken = {{login.response.body.token}}

### save type
POST {{hostname}}/api/type/save HTTP/1.1
Authorization: Bearer {{authToken}} 
Content-Type: {{contentType}}

{
    "name": "traveling"
}

### save turbine
POST {{hostname}}/api/turbine/save HTTP/1.1
Authorization: Bearer {{authToken}} 
Content-Type: {{contentType}}

{
    "number": "postman turbine",
    "location": "Constanta"
}

### save project
POST {{hostname}}/api/project/save HTTP/1.1
Authorization: Bearer {{authToken}} 
Content-Type: {{contentType}}

{
    "name": "postman project",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum nibh a enim vehicula, id luctus felis tempor."
}

### SAVE WARNING
POST {{hostname}}/api/warning/save HTTP/1.1
Authorization: Bearer {{authToken}} 
Content-Type: {{contentType}}

{
    "turbine": "postman turbine",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum nibh a enim vehicula, id luctus felis tempor."
}

### GET WARNINGS
GET {{hostname}}/api/warning/getAll HTTP/1.1
Authorization: Bearer {{authToken}} 
Content-Type: {{contentType}}